services:
  api:
    build: .
    image: go-notification
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_ADDR: redis:6379
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/lib

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongo_data: